name: flutter-app
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22
version: '0.1'
summary: 'Barebones Flutter app'
description: 'count things'


apps:
  flutter-app:
    command: bin/myapp
    extensions: [gnome]

parts:
  flutter-app:
    plugin: flutter
    source: .
    #flutter-branch: master
